global using Microsoft.EntityFrameworkCore;
global using MALO.Microservice.Empresas.Domain.DTOs;
global using MALO.Microservice.Empresas.Domain.DTOs.Usuario;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using MALO.Microservice.Empresas.Aplication.Commons;
global using MALO.Microservice.Empresas.Infraestructure.DataContexts;
global using System.Data;
global using Microsoft.Data.SqlClient;