global using Microsoft.EntityFrameworkCore;
global using MALO.Microservice.Documentos.Domain.DTOs;
global using MALO.Microservice.Documentos.Domain.DTOs.Usuario;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using MALO.Microservice.Documentos.Aplication.Commons;
global using MALO.Microservice.Documentos.Infraestructure.DataContexts;
global using System.Data;
global using Microsoft.Data.SqlClient;
