name: .NET

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2 #descarga el codigo
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1 #configura el ambiente para el framework
      with:
        donet-version: 5.0.x
    - name: restaurar dependencias
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration release # compilar
